services:

  frontend:
    container_name: wayshub-frontend
    image: millinovz/wayshub-frontend:v1
    stdin_open: true
    ports:
      - 3000:3000

  nodexp:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - 9100:9100
    volumes:
     - "/proc:/host/proc:ro"
     - "/sys:/host/sys:ro"
     - "/:/rootfs:ro"
    command:
      - "--web.listen-address=:9100"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.ignored-mount-points='^/(sys|proc|dev|host|etc|rootfs|var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'"

