- name: Check if certbot exist
  command: certbot --version
  register: certbot_valid
  failed_when: false
  changed_when: false

- name: If no certbot, run install certbot
  when: certbot_valid.rc != 0
  include_tasks:
    file: install-certbot.yml

- name: Check if SSL certificate already exists for this domain
  stat:
    path: "/etc/letsencrypt/live/{{ item }}/fullchain.pem"
  register: cert_check

- name: Run certbot
  when: cert_check.stat is defined and cert_check.stat.exists == false
  command: >
    certbot --nginx
    -d {{ item }}
    --non-interactive
    --redirect
    --agree-tos
    -m {{ user_email }}