- name: Adding new user
  hosts: webserver, appserver, monitoring
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:

  - name: Create user with a home directory
    user:
      name: "{{ ansible_user }}"
      shell: /bin/bash
      create_home: yes
      password: $6$Oy365hjctQXT9fsD$hT7n/giJRzurtcLGUSmXwVHvC55GHXcKvIw2yvXl7szOemtahzrumJMT0iqVOjvILAprHwPsTmyLHoeXDRBYd1

  - name: Set authorized_keys for login ssh key
    authorized_key:
      user: "{{ ansible_user }}"
      key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

  - name: Allow authenticate with password
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?PasswordAuthentication\s'
      line: "PasswordAuthentication yes"
      state: present
      validate: '/usr/sbin/sshd -t -f %s'
  
  - name: Add a new rule sshd_config.d/
    copy:
      content: 'PasswordAuthentication yes'
      dest: /etc/ssh/sshd_config.d/99-password.conf
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '644'

  - name: Edit other config
    loop:
      - /etc/ssh/sshd_config.d/50-cloudimg-settings.conf
      - /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
    lineinfile:
      path: "{{ item }}"
      regexp: '^#?PasswordAuthentication\s'
      line: "PasswordAuthentication yes"
      state: present
      validate: '/usr/sbin/sshd -t -f %s'

  - name: Restart SSH
    systemd_service:
      name: ssh
      state: restarted
      daemon_reload: true
