- name: Deploying wayshub-frontend app
  hosts: appserver
  become: true
  tasks:
    - name: Check If Docker Is Installed
      command: docker --version
      register: docker_valid
      ignore_errors: yes
    - name: Debug Docker Output
      debug:
        var: docker_valid
    - name: If no docker
      debug:
        msg: "No docker here, run Docker Install first"
      when: docker_valid.failed
    - name: If yes docker
      debug:
        msg: "Docker is running"
      when: not docker_valid.failed

