- name: Deploying wayshub-frontend app
  hosts: monitoring
  tasks:

    - name: Check If Docker Is Installed
      command: docker --version
      register: docker_valid
      ignore_errors: yes

    - name: Debug Docker Output
      debug:
        var: docker_valid 

    - name: If no docker, run install docker
      when: docker_valid.failed
      args:
        apply:
          become: true 
      include_tasks:
        file: ./tasks/install-docker.yml

    - name: If yes docker are running
      when: not docker_valid.failed
      block:
        - name: Ensure docker directory exists
          ansible.builtin.file:
            path: "{{ ansible_user_dir }}/docker"
            state: directory
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0755'

        - name: Copying docker-compose
          copy:
            src: ./misc/monitoring-compose.yml
            dest: "{{ ansible_user_dir }}/docker/docker-compose.yml"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0755'
        
        - name: Copying Prometheus Config
          copy:
            src: ./misc/prometheus.yml
            dest: "{{ ansible_user_dir }}/docker/prometheus.yml"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0755'
        
        - name: Turn off docker compose first
          command: docker compose down
          args:
            chdir: "{{ ansible_user_dir }}/docker"
        
        - name: Run docker compose
          command: docker compose up -d
          args:
            chdir: "{{ ansible_user_dir }}/docker"


