- name: Nginx Installer
  hosts: webserver
  become: true
  tasks:

    - name: Installing Nginx
      apt:
        name: nginx
        state: latest
        update_cache: true

    - name: Copying Reverse Proxy Settings
      copy:
        src: ./.rev-proxy/frontend.conf
        dest: /etc/nginx/sites-available/frontend.conf
        owner: miral
        group: miral
        mode: '644'
        
    - name: Applying Reverse Proxy Settings
      systemd_service:
        state: restarted
        daemon_reload: true
        name: nginx
