- name: Nginx Installer
  hosts: webserver
  become: true
  tasks:

    - name: Installing Nginx
      apt:
        name: nginx
        state: latest
        update_cache: true

    - name: Copying Reverse Proxy Settings
      copy:
        src: "{{ item }}"
        dest: /etc/nginx/sites-enabled/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '644'
      with_fileglob:
        - "./.rev-proxy/*"

    - name: Applying Reverse Proxy Settings
      systemd_service:
        state: restarted
        daemon_reload: true
        name: nginx
