upstream backend {
        server 34.101.203.222:5000;
}

server {
        server_name api.millinov.studentdumbways.my.id;

        location / {
                        proxy_pass http://backend;
        }
}
