upstream frontend {
        server 10.184.0.4:3000;
}

server {
        server_name millinov.studentdumbways.my.id;

        location / {
                        proxy_pass http://frontend;
        }
}
