upstream grafana {
        server 10.184.0.3:3001;
}

server {
        server_name monitoring-millinov.studentdumbways.my.id;

        location / {
                        proxy_pass http://grafana;
        }
}