upstream nodexp1 {
        server 10.184.0.4:9100;
}

server {
        server_name exporter-1millinov.studentdumbways.my.id;

        location / {
                        proxy_pass http://nodexp1;
        }
}
