upstream prometheus {
        server 10.184.0.3:9090;
}

server {
        server_name prom-millinov.studentdumbways.my.id;

        location / {
                        proxy_pass http://prometheus;
        }
}
